### ISSUE TITLE
Can't get androwarn to work

### ISSUE THREAD

**Issue by CaledoniaProject** [maaaaz/androwarn#12]
I'm unable to run androwarn, do you know what is it connecting to?

The apk is copied from the SampleApplication directory

```
%> ./androwarn.py -v 1 -i mal.apk -r txt
Traceback (most recent call last):
  File "./androwarn.py", line 116, in <module>
    main(options, arguments)
  File "./androwarn.py", line 99, in main
    data = perform_analysis(APK_FILE, a, d, x, no_connection)
  File "/Users/xxxx/Library/Caches/shm/androwarn-master/androwarn/analysis/analysis.py", line 94, in perform_analysis
    app_name, app_desc, app_icon = grab_application_name_description_icon(app_package_name, no_connection)
  File "/Users/xxxx/Library/Caches/shm/androwarn-master/androwarn/search/application/application.py", line 67, in grab_application_name_description_icon
    response = urllib2.urlopen(req, timeout=REQUEST_TIMEOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 65] No route to host>
```

**Comment by maaaaz** [comment]
Hello @CaledoniaProject,

It was connecting to the Play Store in order to get some information about the analyzed application : name, description and icon link.
It is now fixed, as there's no external connection unless specified with the `-w` option.

Best regards.
