### ISSUE TITLE
exception must be old-style classes

### ISSUE THREAD

**Issue by k1ng88** [maaaaz/androwarn#16]
I just installed androwarn and try to scan apk fiile, but getting this error.
Anyone know how to solve it?

Traceback (most recent call last):
  File "androwarn.py", line 116, in <module>
    main(options, arguments)
  File "androwarn.py", line 95, in main
    a, d, x = AnalyzeAPK(APK_FILE)
  File "/root/androwarn/androwarn/analysis/analysis.py", line 48, in AnalyzeAPK
    a = APK(filename, raw)
  File "/root/androwarn/androguard/core/bytecodes/apk.py", line 163, in __init__
    self.xml[i] = minidom.parseString( AXMLPrinter( self.zip.read( i ) ).getBuff() )
  File "/root/androwarn/androguard/core/bytecodes/apk.py", line 871, in __init__
    _type = self.axml.next()
  File "/root/androwarn/androguard/core/bytecodes/apk.py", line 622, in next
    self.doNext()
  File "/root/androwarn/androguard/core/bytecodes/apk.py", line 662, in doNext
    raise("ooo")
TypeError: exceptions must be old-style classes or derived from BaseException, not str

**Comment by maaaaz** [comment]
Hello @k1ng88,

I don't know but I suspect that this errors comes from the fact that the current embedded `androguard` library is really obsolete.

I might soon use a more recent one.

Best regards
