### ISSUE TITLE
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>

### ISSUE THREAD

**Issue by ChenJunHero** [maaaaz/androwarn#17]
when I run the command line `python androwarn.py -i 0a7f7.apk -r html -v 3`,I get the following message

> Traceback (most recent call last):
  File "androwarn.py", line 116, in <module>
    main(options, arguments)
  File "androwarn.py", line 99, in main
    data = perform_analysis(APK_FILE, a, d, x, no_connection)
  File "/home/chenjun/androwarn/androwarn/analysis/analysis.py", line 94, in perform_analysis
    app_name, app_desc, app_icon = grab_application_name_description_icon(app_package_name, no_connection)
  File "/home/chenjun/androwarn/androwarn/search/application/application.py", line 67, in grab_application_name_description_icon
    response = urllib2.urlopen(req, timeout=REQUEST_TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>

The running environment of my computer is ubuntu16.04 ,python2.7 and java1.7.How could I solve this problem?
Thanks.

**Comment by maaaaz** [comment]
Hello,

Your environment does not seem to have an Internet connection, so online lookups (icons, description etc.) fail.
Add the `--no-connection` option to your command line, so it becomes `python androwarn.py -i 0a7f7.apk -r html -v 3 --no-connection`

Cheers.
