### ISSUE TITLE
Unknown Androwarn issue

### ISSUE THREAD

**Issue by StephenQuirolgico** [maaaaz/androwarn#23]
Androwarn had an issue processing this app:

[https://play.google.com/store/apps/details?id=com.epocrates](https://play.google.com/store/apps/details?id=com.epocrates)

I'm using Python 2.7:

Traceback (most recent call last):
File "/data/androwarn/androwarn.py", line 116, in
main(options, arguments)
File "/data/androwarn/androwarn.py", line 95, in main
a, d, x = AnalyzeAPK(APK_FILE)
File "/data/androwarn/androwarn/analysis/analysis.py", line 48, in AnalyzeAPK
a = APK(filename, raw)
File "/data/androwarn/androguard/core/bytecodes/apk.py", line 156, in __init__
self.zip = zipfile.ZipFile( StringIO.StringIO( self.__raw ), mode=mode )
File "/usr/lib64/python2.7/zipfile.py", line 766, in __init__
self._RealGetContents()
File "/usr/lib64/python2.7/zipfile.py", line 853, in _RealGetContents
x._decodeExtra()
File "/usr/lib64/python2.7/zipfile.py", line 388, in _decodeExtra
tp, ln = unpack(

**Comment by maaaaz** [comment]
Hello @StephenQuirolgico,
Unfortunately, this bug is related to `androguard` and not `androwarn`.

Thanks for reporting it !
