### ISSUE TITLE
Androwarn index out of range errors

### ISSUE THREAD

**Issue by StephenQuirolgico** [maaaaz/androwarn#3]
Thomas,

We are getting "Index out of range errors" on some APKs.  Unfortunately, I am not permitted to send the APKs to you for debugging.  However, we can send you the output after running the APKs through androwarn.  Is it possible to update androwarn to provide more debugging information, particularly with "index out of range" errors?  Here is the output from the latest APK with this error:

Traceback (most recent call last):
  File "/home/test/androwarn/androwarn.py", line 116, in <module>
    main(options, arguments)
  File "/home/test/androwarn/androwarn.py", line 99, in main
    data = perform_analysis(APK_FILE, a, d, x, no_connection)
  File "/home/test/androwarn/androwarn/analysis/analysis.py", line 120, in perform_analysis
    ( 'suspicious_connection_establishment',     gather_suspicious_connection_establishment(x) ),
  File "/home/test/androwarn/androwarn/search/malicious_behaviours/remote_connection.py", line 68, in gather_suspicious_connection_establishment
    result.extend( detect_Socket_use(x) ) 
  File "/home/test/androwarn/androwarn/search/malicious_behaviours/remote_connection.py", line 52, in detect_Socket_use
    remote_port     = get_register_value(2, registers)
  File "/home/test/androwarn/androwarn/core/core.py", line 426, in get_register_value
    dict = registers[index]
IndexError: list index out of range

**Comment by Patryck95** [comment]
I'm having the same problem

Traceback (most recent call last):
  File "androwarn.py", line 116, in <module>
    main(options, arguments)
  File "androwarn.py", line 99, in main
    data = perform_analysis(APK_FILE, a, d, x, no_connection)
  File "/home/pc/Documents/TOOLS/Androwarn/androwarn/androwarn/analysis/analysis.py", line 120, in perform_analysis ( 'suspicious_connection_establishment', gather_suspicious_connection_establishment(x) ),
  File "/home/pc/Documents/TOOLS/Androwarn/androwarn/androwarn/search/malicious_behaviours/remote_connection.py", line 68, in gather_suspicious_connection_establishment
    result.extend( detect_Socket_use(x) ) 
  File "/home/pc/Documents/TOOLS/Androwarn/androwarn/androwarn/search/malicious_behaviours/remote_connection.py", line 52, in detect_Socket_use
    remote_port		= get_register_value(2, registers)
  File "/home/pc/Documents/TOOLS/Androwarn/androwarn/androwarn/core/core.py", line 426, in get_register_value
    dict = registers[index]
IndexError: list index out of range

**Comment by dhsgov** [comment]
Unfortunately, I never received a response about this.

**Comment by StephenQuirolgico** [comment]
Unfortunately, I never heard back about this.

**Comment by Patryck95** [comment]
Yeah i've noticed the date XD. I thought that if i posted a new comment perhaps our problem could have some reply.

**Comment by StephenQuirolgico** [comment]
Hi Patryck95,

Unfortunately, I never heard back from maaaaz about this.

Steve

**Comment by maaaaz** [comment]
Hello there,

So long after, that bug is now fixed :)

Best regards.
