### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by tharsh30** [maaaaz/androwarn#30]
hello, am new to python & don't know how to fix this issue...can anybody tell me how to solve it?

kali@kali:~/androwarn$ **python androwarn.py -i SampleApplication.apk -r html -v 3**
[+] Androwarn version 1.6

[+] Loading the APK file...
Traceback (most recent call last):
  File "androwarn.py", line 96, in <module>
    main()
  File "androwarn.py", line 82, in main
    a, d, x = AnalyzeAPK(options.input)
  File "/home/kali/.local/lib/python3.8/site-packages/androguard/misc.py", line 63, in AnalyzeAPK
    a = APK(_file, raw=raw)
  File "/home/kali/.local/lib/python3.8/site-packages/androguard/core/bytecodes/apk.py", line 274, in __init__
    self.__raw = bytearray(read(filename))
  File "/home/kali/.local/lib/python3.8/site-packages/androguard/util.py", line 13, in read
    with open(filename, 'rb' if binary else 'r') as f:
**FileNotFoundError: [Errno 2] No such file or directory: 'SampleApplication.apk'**

**Comment by maaaaz** [comment]
Hello @tharsh30,
I don't understand you want to analyse "FBlite.apk" but the error is about "SampleApplication.apk".

**Comment by tharsh30** [comment]
Am sorry about that....it's just a copy paste error....consider the both as,
SampleApplication.apk
Why am getting like this when I need to scan the related apk? & now I updated that one
