### ISSUE TITLE
AttributeError: 'MethodAnalysis' object has no attribute 'get_code'

### ISSUE THREAD

**Issue by sivaK003** [maaaaz/androwarn#33]
[+] Androwarn version 1.6

[+] Loading the APK file...
Requested API level 31 is larger than maximum we have, returning API level 28 instead.
Traceback (most recent call last):
  File "/home/shan/.local/bin/androwarn", line 8, in <module>
    sys.exit(main())
  File "/home/shan/.local/lib/python3.8/site-packages/androwarn/androwarn.py", line 86, in main
    data = perform_analysis(options.input, a, d, x, options.with_playstore_lookup)
  File "/home/shan/.local/lib/python3.8/site-packages/androwarn/warn/analysis/analysis.py", line 65, in perform_analysis
    ( 'device_settings_harvesting',              gather_device_settings_harvesting(x) ),
  File "/home/shan/.local/lib/python3.8/site-packages/androwarn/warn/search/malicious_behaviours/device_settings.py", line 102, in gather_device_settings_harvesting
    result.extend( detect_log(x) )
  File "/home/shan/.local/lib/python3.8/site-packages/androwarn/warn/search/malicious_behaviours/device_settings.py", line 44, in detect_log
    for registers in data_flow_analysis(structural_analysis_results, x):
  File "/home/shan/.local/lib/python3.8/site-packages/androwarn/warn/core/core.py", line 412, in data_flow_analysis
    registers = backtrace_registers_before_call(x, parent_method, calling_offset)
  File "/home/shan/.local/lib/python3.8/site-packages/androwarn/warn/core/core.py", line 214, in backtrace_registers_before_call
    bc = method.get_code().get_bc()
AttributeError: 'MethodAnalysis' object has no attribute 'get_code'

**Comment by 123zhanglei** [comment]
Hello, I am facing a similar problem as you did. Could you please tell me how you solved it back then? Could you help me out? Thank you very much.

**Comment by movementx** [comment]
I am also getting this same AttributeError, and the report is not being generated.

**Comment by LvHongW** [comment]
[+] Androwarn version 1.6

[+] Loading the APK file...
Requested API level 33 is larger than maximum we have, returning API level 28 instead.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python\Scripts\androwarn.exe\__main__.py", line 7, in <module>
  File "D:\python\Lib\site-packages\androwarn\androwarn.py", line 86, in main
    data = perform_analysis(options.input, a, d, x, options.with_playstore_lookup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\androwarn\warn\analysis\analysis.py", line 65, in perform_analysis
    ( 'device_settings_harvesting',              gather_device_settings_harvesting(x) ),
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\androwarn\warn\search\malicious_behaviours\device_settings.py", line 102, in gather_device_settings_harvesting
    result.extend( detect_log(x) )
                   ^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\androwarn\warn\search\malicious_behaviours\device_settings.py", line 44, in detect_log
    for registers in data_flow_analysis(structural_analysis_results, x):
  File "D:\python\Lib\site-packages\androwarn\warn\core\core.py", line 412, in data_flow_analysis
    registers = backtrace_registers_before_call(x, parent_method, calling_offset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\androwarn\warn\core\core.py", line 214, in backtrace_registers_before_call
    bc = method.get_code().get_bc()
         ^^^^^^^^^^^^^^^
AttributeError: 'MethodAnalysis' object has no attribute 'get_code'.
I am also facing the same issue.

**Comment by emisilve86** [comment]
I did a change in file "D:\python\Lib\site-packages\androwarn\warn\core\core.py" at line 214:

```python
# bc = method.get_code().get_bc()
bc = method.method.get_code().get_bc()
```

and another change at line 415 into the same file:

```python
# method_str  = "Method '%s'" % parent_method.method.get_name()
method_str  = "Method '%s'" % parent_method.method.method.get_name()
```

Then I also modified the file "/home/emiliano/Documenti/Sorgente/GitHub/Androwarn/warn/search/api/api.py" at line 68 as follow:

```python
# New Function to Add
def flatten_classes_hierarchy(d):
    l = []
    for k, v in d.items():
        l.append(k)
        for i in v:
            if isinstance(i, dict):
                l = l + flatten_classes_hierarchy(i)
            else:
                l.append(i)
    return l

def grab_classes_hierarchy(d, x):
    result = []
    for i in d:
        result = result + flatten_classes_hierarchy(i.list_classes_hierarchy())
#       result = result + i.print_classes_hierarchy()
    
    return result
```

This was due the fact that methods get_code() and get_name() belong to the class dex.EncodedMethod of the androguard project, while class DEX only contains a list_classes_hierarchy() that returns a dictionary of lists containing either strings or dictioctionaries of lists, and so on.

These 3 updates definitively work for me, at least for the common usage idicated within the README file.

**Comment by atkinchris** [comment]
Here's @emisilve86 fixes as a diff.

```diff
diff --git a/warn/core/core.py b/warn/core/core.py
index 1ab3b5c..ead9435 100644
--- a/warn/core/core.py
+++ b/warn/core/core.py
@@ -211,7 +211,7 @@ def backtrace_registers_before_call(x, method, calling_index) :
     """ 
     registers = {}
     
-    bc = method.get_code().get_bc()
+    bc = method.method.get_code().get_bc()
     instruction_list = list(bc.get_instructions())
     
     found_index = bc.off_to_pos(calling_index)
@@ -412,7 +412,7 @@ def data_flow_analysis(results, x) :
             registers = backtrace_registers_before_call(x, parent_method, calling_offset)
     
             class_str   = "Class '%s'" % parent_class.orig_class.get_name()
-            method_str  = "Method '%s'" % parent_method.get_name()
+            method_str  = "Method '%s'" % parent_method.method.get_name()
             regs_str    = "Register state before call %s" %  registers
             
             formatted_str = "{0:50}- {1:35}- {2:30}".format(class_str,method_str, regs_str)
diff --git a/warn/search/api/api.py b/warn/search/api/api.py
index 8ec7daf..dec92b2 100644
--- a/warn/search/api/api.py
+++ b/warn/search/api/api.py
@@ -62,10 +62,22 @@ def grab_external_classes_list(d, x) :
     #result.sort()
     return result
 
+# New Function to Add
+def flatten_classes_hierarchy(d):
+    l = []
+    for k, v in d.items():
+        l.append(k)
+        for i in v:
+            if isinstance(i, dict):
+                l = l + flatten_classes_hierarchy(i)
+            else:
+                l.append(i)
+    return l
+
 def grab_classes_hierarchy(d, x):
     result = []
     for i in d:
-        result = result + i.print_classes_hierarchy()
+        result = result + flatten_classes_hierarchy(i.list_classes_hierarchy())
     
     return result
 

```

I needed an additional method change too:

```diff
diff --git a/warn/util/util.py b/warn/util/util.py
index 96fa0bf..2020644 100644
--- a/warn/util/util.py
+++ b/warn/util/util.py
@@ -57,7 +57,7 @@ def log_result_path_information(detectors) :
     for res in detectors :
         xrefs_from = res.get_xref_from()
         for xref_analysis, xref_encodedmethod in xrefs_from:
-            xref_encodedmethod_class, xref_encodedmethod_function, _ = xref_encodedmethod.get_triple()
+            xref_encodedmethod_class, xref_encodedmethod_function, _ = xref_encodedmethod.method.get_triple()
             log.info("'%s' called by function '%s' of class '%s'" % (res.get_value(), xref_encodedmethod_function, xref_encodedmethod_class))
 
 def strip_HTML_tags(html):

```
