### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by harshitSingh1** [maaaaz/androwarn#35]
┌──(root㉿kali)-[/home/kali/Desktop/androwarn-master]
└─# python androwarn.py -i /home/kali/Desktop/ig-learner-master.zip -r html -v 3
Traceback (most recent call last):
  File "/home/kali/Desktop/androwarn-master/warn/search/application/application.py", line 28, in <module>
    import play_scraper
ModuleNotFoundError: No module named 'play_scraper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/androwarn-master/androwarn.py", line 34, in <module>
    from warn.search.search import grab_application_package_name
  File "/home/kali/Desktop/androwarn-master/warn/search/search.py", line 33, in <module>
    from warn.search.application.application import *
  File "/home/kali/Desktop/androwarn-master/warn/search/application/application.py", line 30, in <module>
    sys.exit("[!] The play-scraper module is not installed, please install it and try again")
    ^^^
NameError: name 'sys' is not defined

**Comment by maaaaz** [comment]
Thank you for pointing this "sys" import bug.

Please install these python dependencies: https://github.com/maaaaz/androwarn/blob/master/requirements.txt

**Comment by T4RZH3N** [comment]
pip2 install play_scraper==0.4.0

The latest version of play_scraper 0.6.0 did not work for me and gave me the same error you encountered. Try 0.4.0
